/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package catering.management.system;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author princ
 */
public class Register_Form extends javax.swing.JFrame {

    /**
     * Creates new form Register_Form
     */
    public Register_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelheader = new javax.swing.JPanel();
        lblcna = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jPanelmain = new javax.swing.JPanel();
        lblusernameR = new javax.swing.JLabel();
        lblpasswordR = new javax.swing.JLabel();
        lblphonenoR = new javax.swing.JLabel();
        lblemailR = new javax.swing.JLabel();
        btnregisterR = new javax.swing.JButton();
        txtusernameR = new javax.swing.JTextField();
        txtphonenoR = new javax.swing.JTextField();
        txtemailR = new javax.swing.JTextField();
        lblerror = new javax.swing.JLabel();
        txtpasswordR = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelheader.setBackground(new java.awt.Color(46, 49, 49));

        lblcna.setBackground(new java.awt.Color(255, 255, 255));
        lblcna.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        lblcna.setForeground(new java.awt.Color(255, 255, 255));
        lblcna.setText("Create New Account");

        btnback.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelheaderLayout = new javax.swing.GroupLayout(jPanelheader);
        jPanelheader.setLayout(jPanelheaderLayout);
        jPanelheaderLayout.setHorizontalGroup(
            jPanelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelheaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcna)
                .addGap(148, 148, 148))
        );
        jPanelheaderLayout.setVerticalGroup(
            jPanelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback)
                .addGap(1, 1, 1)
                .addComponent(lblcna)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanelmain.setBackground(new java.awt.Color(238, 238, 238));

        lblusernameR.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        lblusernameR.setText("Username");

        lblpasswordR.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        lblpasswordR.setText("Password");

        lblphonenoR.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        lblphonenoR.setText("Phone Number");

        lblemailR.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        lblemailR.setText("Email");

        btnregisterR.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnregisterR.setText("Register");
        btnregisterR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterRActionPerformed(evt);
            }
        });

        txtusernameR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameRActionPerformed(evt);
            }
        });

        lblerror.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelmainLayout = new javax.swing.GroupLayout(jPanelmain);
        jPanelmain.setLayout(jPanelmainLayout);
        jPanelmainLayout.setHorizontalGroup(
            jPanelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmainLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(jPanelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblemailR)
                    .addComponent(lblphonenoR)
                    .addGroup(jPanelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblpasswordR)
                        .addComponent(lblusernameR)))
                .addGap(41, 41, 41)
                .addGroup(jPanelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtphonenoR)
                    .addComponent(btnregisterR, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtusernameR, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtemailR)
                    .addComponent(lblerror, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(txtpasswordR))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanelmainLayout.setVerticalGroup(
            jPanelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelmainLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelmainLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblusernameR))
                    .addComponent(txtusernameR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpasswordR)
                    .addComponent(txtpasswordR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblphonenoR)
                    .addComponent(txtphonenoR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemailR)
                    .addComponent(txtemailR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblerror, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnregisterR, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jPanelmainLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtemailR, txtpasswordR, txtphonenoR, txtusernameR});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelheader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 117, Short.MAX_VALUE)
                    .addComponent(jPanelmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        Login_Form lf = new Login_Form();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtusernameRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameRActionPerformed

    private void btnregisterRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterRActionPerformed
        // TODO add your handling code here:
        
        String uname,pass,pno,email;
               uname = txtusernameR.getText();
               pass = txtpasswordR.getText();
               pno = txtphonenoR.getText();
               email = txtemailR.getText();
        if (txtusernameR.getText().isEmpty() || txtpasswordR.getText().isEmpty() || txtphonenoR.getText().isEmpty() || txtemailR.getText().isEmpty())
        {
            
            lblerror.setText("Please Fill the Form Correctly");
        }
        else
        {
            ConnectionstoDB con = new ConnectionstoDB();
            con.create(uname, pass, pno, email);
            JOptionPane.showMessageDialog(rootPane, "Account Registered!");
            Login_Form lf = new Login_Form();
            lf.setVisible(true);
            lf.pack();
            lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_btnregisterRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); }       //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Form().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnregisterR;
    private javax.swing.JPanel jPanelheader;
    private javax.swing.JPanel jPanelmain;
    private javax.swing.JLabel lblcna;
    private javax.swing.JLabel lblemailR;
    private javax.swing.JLabel lblerror;
    private javax.swing.JLabel lblpasswordR;
    private javax.swing.JLabel lblphonenoR;
    private javax.swing.JLabel lblusernameR;
    private javax.swing.JTextField txtemailR;
    private javax.swing.JPasswordField txtpasswordR;
    private javax.swing.JTextField txtphonenoR;
    private javax.swing.JTextField txtusernameR;
    // End of variables declaration//GEN-END:variables
}
